name: tellam
description: Tellam flutter package to integrate FAQ and live support chat using firebase.
version: 0.1.3
author: Ambrose Bako<bakoambrose@gmail.com>
homepage: https://github.com/ambrosethebuild/tellam-flutter

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  floor: ^0.13.0
  flutter_icons: ^1.0.0+1
  cached_network_image: ^2.2.0+1
  flutter_html: ^1.0.0
  firebase_database: ^3.1.6
  url_launcher: ^5.5.0
  flutter_gradient_colors: ^1.0.0
  flutter_svg: ^0.18.0
  rxdart: ^0.24.1
  timeago: ^2.0.26
  bubble: ^1.1.9+1
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.13.0
  build_runner: ^1.7.3


flutter:
  uses-material-design: true
  assets:
    - assets/images/